### PR TITLE
Fix more api inconsistencies

### PR DESCRIPTION
**Pull request by alexyao2015**
This adjusts various differences with the API. This should cover everything that is currently implemented including states, lights, and config to bring what we currently return to near 100% adherence to the API. 🎉 

This does not fix missing endpoints, UPnP discovery, etc.

### CODE REVIEW

**Comment by Mr-Groch** [comment]
I've tried this PR, and this change broke discovery of emulated hue from my Philips TV. I'm sensitive at this point, because of issue #41 so wanted to try this PR for regression. And there it is ;)

**Comment by alexyao2015** [comment]
@Mr-Groch Please give it a try now to see if you are still having issues with discovery. Will likely need multiple tests to really narrow down this issue.

**Comment by alexyao2015** [comment]
Also please let me know if the official emulated_hue component within Home Assistant can be detected or not.

**Comment by Mr-Groch** [comment]
Yes, discovery on  my Philips TV now works as before. Also  tried official emulated hue - my TV does not discover it

**Comment by marcelveldt** [comment]
> Yes, discovery on my Philips TV now works as before. Also tried official emulated hue - my TV does not discover it

Official emulated Hue in HA is only a very basic implementation of a V1 Hue bridge so it will not be discovered, not it can be used with any of the official Hue apps, let alone Philips Ambilight TV.

**Comment by marcelveldt** [comment]
I'm fine with this. I'll merge it in.
I see room for improvements though as we're  slowly adding some features but let's handle them when we're refactor some code into controller(s).

**Pull request merged**
