### PR TITLE
Very strange fix to allow f.lux to work

### LINKED ISSUE #59: F.Lux Pairing Issues
**Describe the bug**

F.lux will not pair

```
GET /api
GET /api//lights
```

We need to determine the correct response for those endpoints

**Steps to Reproduce**

**Expected behavior**

**Logs**

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev): 
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Additional context**

### PR DESCRIPTION
**Pull request by alexyao2015**
Why is this required? No idea...
F.lux is very very strange, but this definitely does fix it. 
Fixes #59

### CODE REVIEW

**Comment by marcelveldt** [comment]
I wonder is this breaks anything else ?

**Comment by marcelveldt** [comment]
I want to have a look at this first because this seems strange to me.

**Comment by alexyao2015** [comment]
Yes exactly. It seems extraordinarily strange, but afaik f.lux works now and hue essentials still works as well.

**Comment by alexyao2015** [comment]
This doesn't work?

**Pull request closed without merging**
