### PR TITLE
Preliminary color fix

### PR DESCRIPTION
**Pull request by alexyao2015**
partially for #72, but does not fully resolve it
works as a temporary solution until we find a better way

We will need a real fix in the future

### CODE REVIEW

**Comment by marcelveldt** [comment]
Isn't it true that both color_temp and xy_color are present in the HA state ?

**Comment by alexyao2015** [comment]
It depends. At least in the case of group lights, if all RGB lights are turned off, the xy_color and hs_color disappear from the state.

**Comment by marcelveldt** [comment]
Most attributes will not be present if a light is off. Only when the light is on, these attributes will be present.
Exception is a few defaults like the friendly_name and supported_features

**Comment by alexyao2015** [comment]
resolved in #196

**Pull request closed without merging**
